#**La base de NumPy ndarray**

Toda la libreria de numpy se basa en la estructura de datos conocida como matriz multidimensional o ndarray



#Caracteristicas basicas de un ndarray

* Un ndarray puede contener elementos de **cualquier tipo**
* Todos los elementos del ndarray deben ser del **mismo tipo**
* El tamaño de un ndarray (numero de elemtos) se define al momento de su creación y no se puede modificar
* La organización de los elementos si se puede modificar


#Uso basico de cualquier elemento de NumPy

NumPy **No** es un modulo del nucelo de python por lo que debe ser importado cada vez que se desea usar, ya sea de forma completa o elemento por elemento

In [2]:
import numpy as np

#**Creación de un ndarray** 

Creación de un ndarray vacio

In [4]:
#Especificando dimensiones
array_vacio = np.empty((3,2), dtype = np.unicode)
array_vacio

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: `np.unicode` is a deprecated alias for `np.compat.unicode`. To silence this warning, use `np.compat.unicode` by itself. In the likely event your code does not need to work on Python 2 you can use the builtin `str` for which `np.compat.unicode` is itself an alias. Doing this will not modify any behaviour and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


array([['', ''],
       ['', ''],
       ['', '']], dtype='<U1')

Copiando dimensiones y tipo desde otra estructura

In [5]:
array_vacio_copia = np.empty_like([1,2,3,4,5])
array_vacio_copia

array([57812240,        0,        0,        0,        0])

Creacion de un ndarray de unos

In [7]:
#Especificando dimensiones
array_unos = np.ones((3,2))
array_unos

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
#Copiando dimensiones y tipos desde otra estructura
array_unos_copy = np.ones_like([1,2,3,4,5])
array_unos_copy

array([1, 1, 1, 1, 1])

Creacion de un ndarray de ceros

In [9]:
#Especificando dimensiones
array_ceros = np.zeros((3,2))
array_ceros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
#Copiando dimensiones y tipos desde otra estructura
array_ceros_copy = np.zeros_like([1,2,3,4,5])
array_ceros_copy

array([0, 0, 0, 0, 0])


Creación de una matriz identidad con ndarray

In [12]:
array_identidad = np.identity(3)
array_identidad

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Creacion de un ndarray con unos en las diagonales

In [13]:
#Creacion de un array con unos en la diagonal principal
array_identidad = np.eye(4)
array_identidad

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
#K = 1 Unos en la diagonal por encima de la principal
array_con_segunda_diagonal = np.eye(4, k = 1)
array_con_segunda_diagonal

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [17]:
#Matriz no cuadrada con unos en la diagonal especificada
array_no_cuadrado = np.eye(4, 3, k=-1)
array_no_cuadrado

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Creacion de un ndarray cuyos elementos son una secuencia numerica

In [18]:
#Un parametro = desde 0 (valor incluido) hasta el numero indicado (no incluido)
array_secuencia1 = np.arange(10)
array_secuencia1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
#Dos parametros primer valor (incluido) hasta el segundo valor (no incluido)
array_secuencia2 = np.arange(5,9)
array_secuencia2

array([5, 6, 7, 8])

In [20]:
#tres parametros = primer valor incluido, segundo valor no incluido, tercer valor: saltos
array_secuencia3 = np.arange(5, 20, 2)
array_secuencia3

array([ 5,  7,  9, 11, 13, 15, 17, 19])

Creación de un ndarray apartir de una secuencia basica de Python

In [21]:
#Unidimensional
array_basico = np.array([1,2,3,4,5])
type(array_basico)

numpy.ndarray

In [25]:
#Multidimensional
array_basico_multidimensional = np.array([ [1,2,3,4] , [5,6,7,8,9] ])
array_basico_multidimensional

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  


array([list([1, 2, 3, 4]), list([5, 6, 7, 8, 9])], dtype=object)

# **Tipos de dato en nd arrays de NumPy**

* **Enteros con signo:** np.int8, np.int16, np.int32, npint64
* **Enteros sin signo:** np.unit8, np.unit16, np.unit32, np.unit64
* **Numeros en coma flotante:** np.float16, np.float32, np.float64, np.float128
* **Booleanos:** np.bool
* **Objetos:** np.object
* **Cadenas de caracteres:** np.string\_ , np.unicode\_
* ...

**Especificación / Casting / Conversión de tipos entre ndarrays**

In [26]:
array_inicial_enteros = np.array([1,2,3,4,5], dtype=np.int32) 
array_inicial_enteros

array([1, 2, 3, 4, 5], dtype=int32)

In [28]:
array_float = np.asarray(array_inicial_enteros, dtype=np.float64)
array_float

array([1., 2., 3., 4., 5.])

In [29]:
array_strings = np.array(array_float, dtype=np.unicode_)
array_strings

array(['1.0', '2.0', '3.0', '4.0', '5.0'], dtype='<U32')

> **Consulta de la composicion de un ndarray**

>* **dtype:** Tipo de contenido del array
>* **ndim:** Numero de dimensiones/ejes del array
>* **shape:** Estructura/forma del array, es decir, numero de elementos en cada uno de los ejes/ dimensiones
>* **size:** Numero total de elemntos en el ndarray

In [30]:
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [31]:
#Tipo de dato (unico)
array.dtype

dtype('int64')

In [33]:
#Dimensiones del array
array.ndim

2

In [34]:
#Forma/Dimensiones
array.shape

(3, 4)

In [36]:
#Numero total de elementos
array.size

12

**Operaciones aritmeticas entre ndarrays y escalares**

In [37]:
array = np.array([1,2,3,4,5], dtype=np.float64) 

In [38]:
#Suma
array + 5

array([ 6.,  7.,  8.,  9., 10.])

In [40]:
#Resta
array - 2

array([-1.,  0.,  1.,  2.,  3.])

In [41]:
#Multiplicacion
array * 3

array([ 3.,  6.,  9., 12., 15.])

In [42]:
#Division
1 / array

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ])

In [43]:
#Division entera
array // 2

array([0., 1., 1., 2., 2.])

In [45]:
#Potencia
array ** 2

array([ 1.,  4.,  9., 16., 25.])

In [48]:
#Asignación con operador
array += 1
array

array([3., 4., 5., 6., 7.])

**Operaciones artimeticas entre ndarrays**

**IMPORTANTE:** Deben ser ndarrays de las mismas dimensiones y forma. Se aplica la operacion elemento a elemento